version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "8443:443"
    volumes:
      - ./requirements/nginx/tools/certs:/etc/nginx/certs
      - ./requirements/nginx/tools/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/tools/html:/var/www/html
  # wordpress:
  #   build: 
  #     context: ./requirements/wordpress
  #   ports:
  #     - "9000:9000"