version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/certs:/etc/nginx/certs
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
