# version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "8443:443"
    depends_on:
      - wordpress
    networks:
      - app-network
    volumes:
      - wp_data:/var/www/html
  
  mariadb:
    build:
      context: ./requirements/mariadb/
    ports:
      - "3306:3306"
    environment:
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER:  ${SQL_USER}     
      SQL_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 7s
      retries: 10
      start_period: 20s 



  wordpress:
    build: 
      context: ./requirements/wordpress
    ports:
      - "9000:9000"
    depends_on: 
      mariadb:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: ${DB_HOST}
      DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes: 
      - wp_data:/var/www/html
    restart: always

volumes:
  db_data:
  wp_data:

networks:
  app-network: