version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443" # Expose le port 443 du conteneur sur le port 443 de la machine hôte
    volumes:
      - ./requirements/nginx/certs:/etc/nginx/certs
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
