# version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    ports:
      - "3306:3306"
    environment:
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}     
      SQL_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${SQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s 



  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress/
    ports:
      - "9000:90000"
    depends_on: 
      mariadb:
        condition: service_healthy
    networks:
      - inception
    environment:
      DB_HOST: ${DB_HOST}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes: 
      - wordpress:/var/www/html/wordpress
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ahors/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ahors/data/mariadb
      o: bind
    
networks:
  inception: