services:
  tor-nginx:
    build: .
    container_name: tor-nginx
    volumes:
      - ./html:/var/www/html
      - ./config/nginx.conf:/etc/nginx/sites-available/default
      - ./config/sshd_config:/etc/ssh/sshd_config
      - ./config/torrc:/etc/tor/torrc
    ports:
      - "8080:80"
      - "1234:4242"

