Vagrant.configure("2") do |config|

    config.vm.define "ahors" do |master|
        config.vm.box = "debian/bookworm64"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.hostname = "ahorsS"

        master.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = "1"
            vb.name = "ahorsS"
        end

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/vagrant/provision/playbook.yml"
            ansible.inventory_path = "/vagrant/provision/inventory.ini"
            ansible.become = true
        end
    end
end
